name : "main workflow"

# trigger
on: 
  pull_request:
    branch:
      - dev

jobs:
  build:
    name: "Build laravel App"
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          composer install

      - name: Build the Application
        run: |
          php artisan key:generate

