name : "main workflow"

# trigger
on: 
  pull_request:
    branch:
      - dev

jobs:
  build:
    name: "Build laravel App"
    runs-on: ubuntu-latest
    steps:


      - name: composer install
        run: |
          sudo apt install php-cli unzip
          cd ~
          curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
          HASH=`curl -sS https://composer.github.io/installer.sig`
          php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

      - name : show current directory 
        run: |
        pwd
        ls -la

      - name: Install dependencies
        run: |
          composer install

      

      - name: Build the Application
        run: |
          php artisan key:generate

